# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: 
        steps:
          - bash: | 
              echo $(Build.BuildId)
              echo $(Build.BuildNumber)
              echo $(Build.SourceBranchName)
              echo $(System.DefaultWorkingDirectory)
              echo $(Build.ArtifactStagingDirectory)
              echo "Test"
              echo java -version
              echo node --version
              echo python --version
              echo mvn -version
          - bash: ls -R $(System.DefaultWorkingDirectory)
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          # - task: CopyFiles@2
          #   inputs:
          #     SourceFolder: '$(System.DefaultWorkingDirectory)'
          #     Contents: index.php              
          #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/index.php'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - bash: ls -R $(Build.ArtifactStagingDirectory)
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: DevDeploy
    jobs:
      - deployment: DevDeployJob
        environment: Dev       
        strategy:
          runOnce: 
            deploy:
              steps:
                - bash: echo "Deployment started"
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Azure subscription 1 (1cd44045-c104-4c60-9365-ebbb2050b7b7)'
                    appType: 'webAppLinux'
                    appName: 'varuwebapp-demo'
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    runtimeStack: 'PHP|8.3'
            