# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Checkout
    jobs:
      - job:
        steps:
          - bash: echo "Checkout is done"

  - stage: Build
    jobs:
      - job: 
        steps:
          - checkout: none
          - bash: | 
              echo $(Build.BuildId)
              echo $(Build.BuildNumber)
              echo $(Build.SourceBranchName)
              echo $(System.DefaultWorkingDirectory)
              echo $(Build.ArtifactStagingDirectory)
              echo "Test"
              echo java -version
              echo node --version
              echo python --version
              echo mvn -version
          - bash: ls -R $(Build.ArtifactStagingDirectory)
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                **/*.php
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - bash: ls -R $(Build.ArtifactStagingDirectory)
